# fly.toml app configuration file generated for weathered-wildflower-9587 on 2023-06-25T19:19:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-wildflower-9587"
primary_region = "mia"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
